<script>
    require([
        'jquery',
        'prototype'
    ], function(jQuery){
        let collectSpan = jQuery('#collect_span');

        jQuery('#download_multisafepay_log').click(function () {
            new Ajax.Request('<?php echo $block->escapeUrl($block->getLogUrl()) ?>', {
                loaderArea: false,
                asynchronous: true,
                onCreate: function() {
                    collectSpan.find('.collected').hide();
                    collectSpan.find('.processing').show();
                    jQuery('#collect_message_span').text('');
                },
                onSuccess: function(response) {
                    collectSpan.find('.processing').hide();

                    let resultText = '';
                    if (response.status > 200) {
                        resultText = response.statusText;
                    } else {
                        resultText = 'File downloaded';
                        collectSpan.find('.collected').show();
                    }
                    jQuery('#collect_message_span').text(resultText);
                }
            });
        });

    });
</script>
<div style="margin-bottom: 10px;"><?= $block->getLogButtonHtml()?>
    <span class="collect-indicator" id="collect_span">
        <img class="processing" hidden="hidden" alt="Collecting" style="margin:0 5px" src="<?php echo $block->getViewFileUrl('images/process_spinner.gif') ?>"/>
        <img class="collected" hidden="hidden" alt="Collected" style="margin:-3px 5px" src="<?php echo $block->getViewFileUrl('images/rule_component_apply.gif') ?>"/>
        <span id="collect_message_span"></span>
    </span>
</div>
<div><?= $block->getDebugLogButtonHtml()?></div>
