<?php

use MultiSafepay\ConnectAdminhtml\Block\Adminhtml\Config\Download\Button;

/** @var Button $block */
/** @var Magento\Framework\Escaper $escaper */
/** @var Magento\Framework\View\TemplateEngine\Php $this */
?>
<script>
    require([
        'jquery',
        'prototype'
    ], function(jQuery){
        jQuery('#download_multisafepay_log').click(function () {
            window.open('<?= $escaper->escapeUrl($block->getLogUrl())?>');
        });
    });
</script>
<?= $block->getLogButtonHtml()?>
