<?php
/**
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is provided with Magento in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 * See DISCLAIMER.md for disclaimer details.
 */

declare(strict_types=1);

use MultiSafepay\ConnectAdminhtml\Block\Adminhtml\Config\Support\Support;

// phpcs:disable Generic.Files.LineLength.TooLong

/** @var Magento\Framework\View\TemplateEngine\Php $this */
/** @var Support $block */

$newVersionData = $block->isNewVersionAvailable()
?>
<div id="multisafepay-support" class="multisafepay-support-information">
    <div id="multisafepay-support-banner"></div>
    <div class="multisafepay-support-section">
        <h2 id="multisafepay-title"><?= $block->getEscaper()->escapeHtml(__('Installed version')) ?></h2>
        <table id="version-table">
            <tr class="no-padding-top">
                <td class="version-table-row version-table-row-text">
                    <?= $block->getEscaper()->escapeHtml('Current MultiSafepay version:')?>
                </td>
                <td class="version-table-row">
                    <span class="<?php if ($newVersionData):?> multisafepay-version-update <?php endif;?>
                multisafepay-version-last-version multisafepay-bold version-value">
                        <?= $block->getEscaper()->escapeHtml($block->getModuleVersion()) ?>
                    </span>
                </td>
            </tr>

            <?php if ($newVersionData): ?>
                <tr class="no-padding-top">
                    <td class="version-table-row">
                        <?= $block->getEscaper()->escapeHtml('New version is available:')?>
                    </td>
                    <td class="version-table-row">
                        <div class="new-version">
                        <span class="multisafepay-bold download version-value">
                            <a href="<?= $block->getEscaper()->escapeUrl($newVersionData['url']) ?>"
                               target="_blank"><?= $block->getEscaper()->escapeHtml($newVersionData['version']) ?></a>
                        </span>
                            <p>
                                <a href="<?= $block->getEscaper()->escapeUrl($block->getUpdateDocsLink()) ?>"
                                   target="_blank" class="btn multisafepay-btn-primary multisafepay-btn-primary-link">
                                    <?= $block->getEscaper()->escapeHtml(__('How to update?')) ?>
                                </a>
                            </p>
                        </div>
                    </td>
                </tr>
            <?php endif; ?>
        </table>
        <h2 id="multisafepay-title"><?= $block->getEscaper()->escapeHtml(__('Version support')) ?></h2>
        <table>
            <tr>
                <td class="version-table-row multisafepay-bold">
                    <p><?= $block->getEscaper()->escapeHtml('Open Source: 2.3.x, 2.4.x ')?></p>
                    <p><?= $block->getEscaper()->escapeHtml('Adobe Commerce: 2.3.x, 2.4.x')?></p>
                </td>
            </tr>
        </table>
    </div>

    <div class="multisafepay-support-section">
        <h2 id="multisafepay-title"><?= $block->getEscaper()->escapeHtml(__('Documentation')) ?></h2>
        <?php $msg = 'Read our documentation for more information about MultiSafepay and how to get started:' ?>
        <p><?= $block->getEscaper()->escapeHtml(__($msg)) ?></p>
            <a class="multisafepay-support-button-docs"
               href="https://docs.multisafepay.com/docs/magento-2"
               target="_blank">
                <?= $block->getEscaper()->escapeHtml(__('Manual')) ?>
            </a>
            <a class="multisafepay-support-button-docs"
               href="https://github.com/MultiSafepay/magento2/blob/master/CHANGELOG.md"
               target="_blank">
                <?= $block->getEscaper()->escapeHtml(__('Changelog')) ?>
            </a>
        <p><?= $block->getEscaper()->escapeHtml(__('For developers:')) ?></p>
            <a class="multisafepay-support-button-docs"
               href="https://docs.multisafepay.com/reference/introduction"
               target="_blank">
                <?= $block->getEscaper()->escapeHtml(__('API Documentation')) ?>
            </a>
            <a class="multisafepay-support-button-docs"
               href="https://github.com/MultiSafepay/magento2"
               target="_blank">
                <?= $block->getEscaper()->escapeHtml('MultiSafepay Github') ?>
            </a>

        <p class="multisafepay-support-contact">
            <?= $block->getEscaper()->escapeHtml(__('Didn\'t find a solution or need assistance? Feel free to contact our integration team:')) ?>
            <a class="multisafepay-btn-primary multisafepay-support-button-contact"
               href="mailto:integration@multisafepay.com">
                <?= $block->getEscaper()->escapeHtml('Contact Us') ?>
            </a>
        </p>
    </div>
    <div class="multisafepay-support-section">
        <h2 id="multisafepay-title"><?= $block->getEscaper()->escapeHtml(__('Account')) ?></h2>
        <p class="multisafepay-lh">
            <?= $block->getEscaper()->escapeHtml(__('To use this plugin you need a MultiSafepay account.')) ?>
            <a class="multisafepay-btn-primary multisafepay-support-button-signup"
               href="https://merchant.multisafepay.com/signup"
               target="_blank">
                <?= $block->getEscaper()->escapeHtml('Sign Up') ?>
            </a>
            <br />
            <?php $link = $block->getEscaper()->escapeUrl('https://testmerchant.multisafepay.com/signup');
            $msg = 'If you would like to have a clear overview of what MultiSafepay has to offer, ';
            $msg .= 'feel free to create a %1test account%2'; ?>
            <?= /** @escapeNotVerified */ __($msg, '<a href="' . $link . '" target="_blank">', '</a>') ?>
        </p>
    </div>
    <h2 id="multisafepay-title"><?= $block->getEscaper()->escapeHtml(__('Bring new ideas or make a contribution')) ?></h2>
    <p class="multisafepay-lh">
        <?= $block->getEscaper()->escapeHtml(__('We look forward to receiving your input. Have you seen an opportunity to change things for the better?')) ?>
        <a class="multisafepay-second-primary multisafepay-support-feature-request"
           href="https://github.com/MultiSafepay/magento2/issues/new?assignees=&labels=&template=feature_request.md&title="
           target="_blank">
            <?= $block->getEscaper()->escapeHtml('Feature Request') ?>
        </a>
    </p>
    <p class="multisafepay-lh">
        <?= $block->getEscaper()->escapeHtml(__('For developers: Are we missing something and do you know how to fix it? You are welcome to create a pull request on our Github repository')) ?>
        <a class="multisafepay-support-bug-report"
           href="https://github.com/MultiSafepay/magento2"
           target="_blank"></a>
    </p>
    <p class="multisafepay-lh">
        <?= $block->getEscaper()->escapeHtml(__('What will you get in return? An awesome t-shirt with a special and unique theme, that is designed specifically by MultiSafepay for contributors!')) ?>
    </p>
</div>
